### PR TITLE
Fixed an issue when compiling header file for WatchOS framework target

### PR DESCRIPTION
**Pull request by ezathashim**

### CODE REVIEW

**Comment by keeshux** [comment]
@ezathashim it's the third PR for the same issue. Please take your time and be more accurate, I can't test this thoroughly now. Thanks for your contributions!

**Comment by ezathashim** [comment]
Yes, sorry. The problem was only found when I linked the framework into another project. There were no actual compiling issues in the openssl-apple project, so it was not immediately obvious.

**Comment by keeshux** [comment]
@ezathashim I'm getting this consistently when including a WatchOS target:

```
$ ./create-openssl-framework.sh dynamic
Assembling .dylib for WatchOS 6.0 (arm64_32)
Assembling .dylib for WatchOS 6.0 (armv7k)
Assembling .dylib for WatchSimulator 6.0 (i386)
ld: building for iOS, but linking in object file (obj/a_bitstr.o) built for watchOS Simulator, file 'obj/a_bitstr.o' for architecture i386
```

**Comment by keeshux** [comment]
Found the issue. Check against `WatchSimulator`, not `WatchOSSimulator`.

Anyway, my fault for not testing all these PRs (this is broken as well). I'm gonna force push your squashed submissions to `master` because the history has become overly confusing.

**Pull request closed without merging**
